services:
  - type: web
    name: heroBooks
    env: node
    plan: free
    nodeVersion: 22
    buildCommand: pnpm install && pnpm dlx prisma generate && pnpm build
    startCommand: pnpm dlx prisma migrate deploy && pnpm start
